version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  jobs:
    post_install:
      - pip install --upgrade pdm
      - pdm use $(which python)
      # pandoc fails in isolation mode
      - pdm install --no-isolation --dev -G docs -G viz
