version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  jobs:
    post_install:
      - export VIRTUAL_ENV=$(dirname $(dirname $(which python)))
      - env
      - which pip
      - which python
      - realpath $(which python)
      - ls -la $(dirname $(which python))
      - pip install --upgrade pdm
      # - pdm use $(which python)
      - VIRTUAL_ENV=$(dirname $(dirname $(which python))) pdm info
      - pip list -v
      # pandoc fails in isolation mode
      - pdm install -vv --no-isolation --dev -G docs -G viz
      - pip list -v
