version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  jobs:
    post_install:
      - pip install --upgrade pdm
      # https://github.com/pdm-project/pdm/discussions/1365#discussioncomment-3581356
      # NOTE: pandoc fails in isolation mode
      - VIRTUAL_ENV=$(dirname $(dirname $(which python))) pdm install --no-isolation -G viz -dG docs
