version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  jobs:
    post_install:
      - env
      - which pip
      - which python
      - realpath $(which python)
      - ls -l $(dirname $(which python))
      - pip install --upgrade pdm
      - pdm use $(which python)
      - pdm info
      - pip list -v
      # pandoc fails in isolation mode
      - pdm install -vv --no-isolation --dev -G docs -G viz
      - pip list -v
