version: 2

sphinx:
  configuration: docs/conf.py

# https://github.com/readthedocs/readthedocs.org/issues/4912#issuecomment-1143587902
build:
  os: ubuntu-20.04
  tools:
    python: '3.8'
  jobs:
    post_install:
      - pip install poetry==1.1.13
      - poetry config virtualenvs.create false
      - poetry install --no-dev -E docs -E viz