version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  jobs:
    post_install:
      - pip install --upgrade pdm
      - pdm install --dev -G docs -G viz
