"""
This type stub file was generated by pyright.
"""

import os
from .thing import Thing

STAC_VERSION = os.getenv('STAC_VERSION', '1.0.0-beta.2')
class Catalog(Thing):
    def __init__(self, data, root=..., **kwargs) -> None:
        """ Initialize a catalog with a catalog file """
        ...
    
    @property
    def stac_version(self):
        """ Get the STAC version of this catalog """
        ...
    
    @property
    def description(self):
        """ Get catalog description """
        ...
    
    @classmethod
    def create(cls, id=..., title=..., description=..., root=..., **kwargs):
        """ Create new catalog """
        ...
    
    def children(self):
        """ Get child links """
        ...
    
    def catalogs(self):
        """ Recursive get all catalogs within this Catalog """
        ...
    
    def collections(self):
        """ Recursively get all collections within this Catalog """
        ...
    
    def items(self):
        """ Recursively get all items within this Catalog """
        ...
    
    def add_catalog(self, catalog, basename=...):
        """ Add a catalog to this catalog """
        ...
    
    def add_collection(self, catalog, basename=...):
        """ Add a collection to this catalog """
        ...
    


