"""
This type stub file was generated by pyright.
"""

import logging
import functools
from .catalog import Catalog

logger = logging.getLogger(__name__)
class Collection(Catalog):
    '''
    def __init__(self, *args, **kwargs):
        """ Initialize a scene object """
        super(Collection, self).__init__(*args, **kwargs)
        # determine common_name to asset mapping
        # it will map if an asset contains only a single band
    '''
    @property
    def title(self):
        ...
    
    @property
    def keywords(self):
        ...
    
    @property
    def version(self):
        ...
    
    @property
    def license(self):
        ...
    
    @property
    def providers(self):
        ...
    
    @property
    def extent(self):
        ...
    
    @property
    def summaries(self):
        """ Get dictionary of summaries """
        ...
    
    @functools.lru_cache()
    def parent_catalog(self, item, path_template):
        """ Given relative filename to a new Item find parent catalog """
        ...
    
    def add_item(self, item, filename_template=...):
        """ Add an item to this collection """
        ...
    


