"""
This type stub file was generated by pyright.
"""

import logging
import os
from typing import Any, Dict
from satstac import Thing

logger = logging.getLogger(__name__)
FILENAME_TEMPLATE = os.getenv('SATSEARCH_FILENAME_TEMPLATE', '${collection}/${date}/${id}')
class Item(Thing):
    def __init__(self, *args, **kwargs) -> None:
        """ Initialize a scene object """
        ...

    def collection(self):
        """ Get Collection info for this item """
        ...

    @property
    def properties(self) -> Dict[str, Any]:
        """ Get dictionary of properties """
        ...

    def __getitem__(self, key):
        """ Get key from properties """
        ...

    @property
    def date(self):
        ...

    @property
    def datetime(self):
        ...

    @property
    def geometry(self):
        ...

    @property
    def bbox(self):
        """ Get bounding box of scene """
        ...

    @property
    def assets(self) -> Dict[str, Any]:
        """ Return dictionary of assets """
        ...

    @property
    def assets_by_common_name(self):
        """ Get assets by common band name (only works for assets containing 1 band """
        ...

    def asset(self, key):
        """ Get asset for this key OR common_name """
        ...

    def get_path(self, template):
        """ Substitute envvars in template with Item values """
        ...

    def download_assets(self, keys=..., **kwargs):
        """ Download multiple assets """
        ...

    def download(self, key, overwrite=..., filename_template=..., requester_pays=..., headers=...):
        """ Download this key (e.g., a band, or metadata file) from the scene """
        ...



